### ISSUE TITLE
Throwing warning when used with latest version of React (15.6.1)

### ISSUE THREAD

**Issue by kevinmanncito** [iMerica/django-react-csrftoken#2]
Screenshot of warning:

![screen shot 2017-09-11 at 4 24 16 pm](https://user-images.githubusercontent.com/2521298/30299613-b44d34be-970d-11e7-9d29-687e73d547cc.png)

Should be pretty easy to fix:

```
import React from 'react';
import ReactDOM from 'react-dom';
import cookie from 'react-cookie';

class DjangoCSRFToken extends React.Component {
  constructor() {
    super();
    this.state = {
      csrfToken: cookie.load('csrftoken'),
    };
  }
  render() {
    return (
      ReactDOM.input(
        {
          type: 'hidden',
          name: 'csrfmiddlewaretoken',
          value: this.state.csrfToken
        }
      )
    );
  }
}

export default DjangoCSRFToken;

```

Thoughts?  Thanks for putting this little package together btw

**Comment by iMerica** [comment]
Thanks for raising this issue. I've pushed a branch that moves to the new library.

Can you try testing it out? If the API is the same, there should be no issues. To upgrade to this version, you can use the following in your package.json file.


```
"django-react-csrftoken": "iMerica/django-react-csrftoken#react-dom-factories-upgrade",
```

**Comment by kevinmanncito** [comment]
Looks good, just tested it in a few of my components that are using the `DjangoCSRFToken` and it is working. And the warning is gone

**Comment by iMerica** [comment]
Fixed in https://github.com/iMerica/django-react-csrftoken/pull/3.
